Update French translation
topjohnwu/Magisk pull request #3364
Opened 2020-10-17 13:22 UTC by xerta555

According to https://github.com/topjohnwu/Magisk/commit/2e4dc91b964597016eecf007a14dfea0ad1d4fb2#diff-5e01f7d37a66e4ca03deefc205d8e7008661cdd0284a05aaba1858e6b7bf9103, https://github.com/topjohnwu/Magisk/commit/2760f37e6bc3e708f046d40e83f43a76d6e1de0e#diff-5e01f7d37a66e4ca03deefc205d8e7008661cdd0284a05aaba1858e6b7bf9103 and https://github.com/topjohnwu/Magisk/commit/9087207dc0326f917370032ecca7ddc0779e79b7#diff-5e01f7d37a66e4ca03deefc205d8e7008661cdd0284a05aaba1858e6b7bf9103.

And 1 typo fixed.

2020-10-18 10:26 UTC, DevDef requested changes

2020-10-18 10:26 UTC, DevDef commented on app/src/main/res/values-fr/strings.xml
> +    <string name="no_info_provided">(Aucune info transmise)</string>
No capital letter after an opening parenthesis in French. Please keep the original:
```xml
 <string name="no_info_provided">(aucune info transmise)</string>
```

2020-10-19 21:43 UTC, DevDef approved these changes

2020-10-19 21:44 UTC, DevDef approved these changes

2020-10-21 07:39 UTC, topjohnwu approved these changes

2020-10-21 07:40 UTC, merged