new update values-cs
topjohnwu/Magisk pull request #3685
Opened 2021-01-14 06:38 UTC by LLZN

update czech strings.xml

2021-01-14 18:03 UTC, akkim31 commented
#3637

2021-01-14 18:03 UTC, akkim31 approved these changes

2021-01-14 18:04 UTC, akkim31 approved these changes
#3637

2021-01-14 18:04 UTC, akkim31 approved these changes
#3637

2021-01-14 18:05 UTC, akkim31 requested changes
#3637

2021-01-16 05:31 UTC, topjohnwu approved these changes

2021-01-16 05:31 UTC, merged