Update Greek translation
topjohnwu/Magisk pull request #3862
Opened 2021-02-16 21:56 UTC by grmasa

2021-02-17 18:59 UTC, DenyDarko commented on app/src/main/res/values-el/strings.xml
> +    <string name="modules">Aρθρώματα</string>
Επεκτάσεις

2021-02-17 19:00 UTC, DenyDarko commented on app/src/main/res/values-el/strings.xml
> +    <string name="loading">Φόρτωση…</string>
Φόρτωση (χωρίς τελιτσες)

2021-02-17 19:00 UTC, DenyDarko commented on app/src/main/res/values-el/strings.xml
> +    <string name="not_available">N/A</string>
Μη διαθέσιμο. Το Ν/Α σημαίνει Not Applicable που είναι άλλη ερμηνεία

2021-02-17 19:01 UTC, DenyDarko commented on app/src/main/res/values-el/strings.xml
> +    <string name="home_installed_version">Εγκαταστάθηκε</string>
Τρέχουσα έκδοση

2021-02-17 19:02 UTC, DenyDarko commented on app/src/main/res/values-el/strings.xml
> +    <string name="home_support_title">Υποστήριξε μας</string>
Υποστήριξη

2021-02-17 19:03 UTC, DenyDarko commented on app/src/main/res/values-el/strings.xml
> +    <string name="recovery_mode">Λειτουργία επαναφοράς</string>
Μέσω Recovery mode (το recovery mode στη προκειμένη είναι καλύτερο να μη μεταφραστεί ως κοινός ορισμός)

2021-02-17 19:04 UTC, DenyDarko commented on app/src/main/res/values-el/strings.xml
> +    <string name="install_start">Ξεκινάμε</string>
Εκκίνηση

2021-02-17 19:04 UTC, DenyDarko commented on app/src/main/res/values-el/strings.xml
> +    <string name="install_inactive_slot">Εγκατάσταση σε ανενεργό Slot (Μετά το OTA)</string>
ΣΤΟ ανενεργό slot.

Μετά ΑΠΟ ΟΤΑ

2021-02-17 19:06 UTC, DenyDarko commented on app/src/main/res/values-el/strings.xml
> +    <string name="home_latest_version">Τελευταίο</string>
Διαθέσιμη έκδοση

2021-02-17 19:07 UTC, DenyDarko commented on app/src/main/res/values-el/strings.xml
> +    <string name="forever">Πάντα</string>
Μόνιμα

2021-02-17 19:08 UTC, DenyDarko commented on app/src/main/res/values-el/strings.xml
> +    <string name="menuClearLog">Εκκαθάριση αρχείου καταγραφής τώρα</string>
Το "τώρα" δε χρειάζεται

2021-02-17 19:09 UTC, DenyDarko commented on app/src/main/res/values-el/strings.xml
> +    <string name="safetynet_attest_success">Επιτυχία!</string>
Η πιστοποίηση ήταν επιτυχής

2021-02-17 19:11 UTC, DenyDarko commented on app/src/main/res/values-el/strings.xml
> +    <string name="hide_filter_hint">Φιλτράρετε κατά όνομα</string>
Φιλτράρισμα

2021-02-17 19:12 UTC, DenyDarko commented on app/src/main/res/values-el/strings.xml
> +    <string name="hide_scroll_up">Μετακινηθείτε προς τα επάνω</string>
Μετακίνηση

2021-02-17 19:14 UTC, DenyDarko commented on app/src/main/res/values-el/strings.xml
> +    <string name="repo_cache_cleared">Η Repo cache καθαρίστηκε</string>
Πραγματοποιήθηκε εκκαθάριση της  προσωρινής μνήμης του Repository

2021-02-17 19:15 UTC, DenyDarko commented on app/src/main/res/values-el/strings.xml
> +    <string name="flashing">Γίνεται flash…</string>
Προγραμματισμός σε εξέλιξη

2021-02-17 19:15 UTC, DenyDarko commented on app/src/main/res/values-el/strings.xml
> +    <string name="done">Εγινε!</string>
Ολοκληρώθηκε

2021-02-17 19:15 UTC, DenyDarko commented on app/src/main/res/values-el/strings.xml
> +    <string name="failure">Απέτυχε!</string>
Αποτυχία

2021-02-17 19:16 UTC, DenyDarko commented on app/src/main/res/values-el/strings.xml
> +    <string name="restore_done">Η ανάκτηση έγινε!</string>
Η επαναφορά πραγματοποιήθηκε

2021-02-17 19:18 UTC, DenyDarko requested changes
Έβαλα μερικά συντακτικά/γραμματικά line comments. Και προσωπικά δεν είμαι fan στις τελιτσες προόδου μέσα σε strings.☺️

2021-02-17 19:19 UTC, grmasa commented on app/src/main/res/values-el/strings.xml
> +    <string name="loading">Φόρτωση…</string>
Το πήρα από το αγγλικό κείμενο που είναι:
    <string name="loading">Loading…</string>

2021-02-20 09:51 UTC, topjohnwu approved these changes

2021-02-20 09:51 UTC, merged