Update RU strings
topjohnwu/Magisk pull request #3902
Opened 2021-02-24 00:13 UTC by Displax

2021-02-24 03:38 UTC, yurikoles requested changes

2021-02-24 03:38 UTC, yurikoles commented on stub/src/main/res/values-ru/strings.xml
> +    <string name="no_internet_msg">Пожалуйста, подключитесь к интернету! Требуется обновление приложения Magisk.</string>
`Magisk Manager` is the proper noun of the app, but you changed it to `Magisk application`, which loses sense.

@Displax, аналогия: ОС Окна от Мелкомягких.

2021-02-24 03:38 UTC, yurikoles commented on stub/src/main/res/values-ru/strings.xml
> +    <string name="no_internet_msg">Пожалуйста, подключитесь к интернету! Требуется обновление приложения Magisk.</string>
МежДелМаш поглотил Красную Шапочку :)

2021-02-24 07:17 UTC, Displax commented
@yurikoles 
Менеджера больше нет.
https://github.com/topjohnwu/Magisk/blob/master/docs/releases/22000.md#magisk-manager-is-deadlong-live-the-magisk-app
Упоминания слова "manager" удалено отовсюду и заменено на "app".
https://github.com/topjohnwu/Magisk/commit/b9669f54f739d3d72c579f3f6847965f4bd5119d
https://github.com/topjohnwu/Magisk/commit/6951d926f7affde1cd7965be6e5ce6091f90c798
https://github.com/topjohnwu/Magisk/commit/75584e2b198b5595c748a73750e2e1d6dbfc629e#diff-5e01f7d37a66e4ca03deefc205d8e7008661cdd0284a05aaba1858e6b7bf9103

2021-02-24 10:08 UTC, topjohnwu commented
@Displax may you please remove this commit 843dd4bdd4ff3acaf2ae2d99901f4c1c86006ab3? Thank you

2021-02-24 20:31 UTC, Displax commented
@topjohnwu Done!

2021-02-26 03:54 UTC, topjohnwu approved these changes

2021-02-26 03:54 UTC, merged