Fix overflow
topjohnwu/Magisk pull request #4071
Opened 2021-03-20 16:23 UTC by shakalaca

2021-03-21 19:27 UTC, osm0sis commented
Is this sufficient to fix #4049?

2021-03-22 12:53 UTC, shakalaca commented
oh yes, somehow the comments were lost .. lol

2021-03-23 16:24 UTC, dwdjanika requested changes

2021-03-23 16:24 UTC, dwdjanika commented on native/jni/magiskboot/bootimg.cpp
> +        if (totalsize > end - curr)
#

2021-03-24 10:02 UTC, topjohnwu approved these changes

2021-03-24 10:02 UTC, merged