Only touch vbmeta->flags on seandroid kernels
topjohnwu/Magisk pull request #4906
Opened 2021-11-08 12:52 UTC by Fox2Code

See #4901 

MIUI Device require 0 to boot properly
But some custom ROMs may have set this flag to 3 to boot properly

So only touch this flag when we really need it.

2021-11-08 12:56 UTC, osm0sis approved these changes

2021-11-08 12:58 UTC, vvb2060 requested changes
Only MIUI Android 11 is special, all other normal devices should be set to 3

2021-11-08 13:01 UTC, vvb2060 commented
https://twitter.com/Hikari_Calyx/status/1368542481692856322 cc @HikariCalyx

2021-11-08 13:04 UTC, Fox2Code commented
@vvb2060 is there a way to detect MIUI Android 11 kernels on the Magisk side?
I don't think there is proper fix for this now, but at least we are getting more and more information about the issue.

2021-11-08 13:45 UTC, Fox2Code commented
@vvb2060 I agree, but is there a way to still set the flag to 3 and not cause a boot loop?
By watching all the code you sent in the channel I think I might a a theory of why the device crash when AVB is disabled.
Normally AVB when enabled set flags like is boot ok, (green/orange/red) and many things like this, by disabling AVB the flags in `cmdline` are not set (Doesn't exists), so maybe by trying to search something that doesn't exists in `cmdline` it make the device crash and bootloop.
So maybe magisk should override `cmdline`/`bootconfig` and add dummy values for AVB to make the values actually exists.

This method add AVB properties to the `cmdline`
https://cs.android.com/android/_/android/platform/external/avb/+/ddab37d0073e2108aa57709e9c852e3bd8e56f68:libavb/avb_cmdline.c;l=210

But if `AVB_VBMETA_IMAGE_FLAGS_VERIFICATION_DISABLED` aka `0x2` is set, this method is not called anywhere.
https://cs.android.com/android/_/android/platform/external/avb/+/ddab37d0073e2108aa57709e9c852e3bd8e56f68:libavb/avb_slot_verify.c;l=1536

So I theory I think it's possible to "fix" MIUI boot by providing stub values to the cmdline.
But note that it's only a theory and I am not 100% sure this is because of this AVB is required.

This is a really a common issue of programs/systems assuming X or Y and crashing when their assumption are not true.
So I am feeling this is the most plausible reason why MIUI is crashing.

@vvb2060 could you try to make a pull request that add dummy AVB values to `cmdline`, and make MIUI users test this.
I know it's possible to append `cmdline` arguments with `magiskboot` since I already done this for a friend in the past.

2021-11-08 15:24 UTC, yujincheng08 commented
We should add an extra checkbox for this flag like:
https://github.com/topjohnwu/Magisk/blob/f42a87b51ae64cf5ed4937e3cd17c7f865f33bc1/app/src/main/res/layout/fragment_install_md2.xml#L93-L100
and we could then check whether to set this flag to `3` on the Magisk app.

2021-11-08 15:37 UTC, Fox2Code commented
Yeah maybe it's the best solution, but the `0x3` is already disabling `dm-verity`, at least on the bootloader side, maybe we should revive `keep_dm_verity` for Andorid 10+ (Andorid is SAR since Andorid 10, so this switch is not visible on Android 11.)

2021-11-12 20:54 UTC, Gong-Mi commented
Confirm that Samsung MediaTek needs this "3" 
Will the production of mobile phones after "3" also require "3"
Doubt 

这个需要用“3”才能开机手机就三星的联发科手机吧。
最早提交这个“3”之后生产的手机，有没有可能也需要。

2021-11-18 12:53 UTC, carey036 commented
this magisk work not well on redmi k40g.

this magisk changed "**03** 00 00 00 00 00 00 00 00 61 76 62 74 6F 6F 6C 20" to "00 00 00 00 **01** 00 00 00 00 61 76 62 74 6F 6F 6C 20", instead of "**01** 00 00 00 00 00 00 00 00 61 76 62 74 6F 6F 6C 20"

by the way, "**01** 00 00 00 00 00 00 00 00 61 76 62 74 6F 6F 6C 20" works well on redmi k40g

2021-11-20 00:11 UTC, Fox2Code commented
@carey036 thank for reporting this weird behavior, I will do a quick fix then to fix that.

2021-11-20 02:38 UTC, osm0sis commented
@carey036 @ahxxm @qianmo-xw try the app-debug.apk in this Artifacts zip: https://github.com/topjohnwu/Magisk/actions/runs/1483248807

2021-11-20 05:17 UTC, carey036 commented
> @carey036 @ahxxm @qianmo-xw try the app-debug.apk in this Artifacts zip: https://github.com/topjohnwu/Magisk/actions/runs/1483248807

It seems that the patched boot.img has no change, same question with before.

2021-11-20 12:31 UTC, Gong-Mi commented
https://github.com/Gong-Mi/Magisk/actions/runs/1484231555


K40g can be used

2021-11-20 12:37 UTC, Gong-Mi commented
> https://github.com/Gong-Mi/Magisk/actions/runs/1484231555
> 
> 
> K40g can be used 

OnePlus7 pro Can be started

2021-11-20 12:42 UTC, Gong-Mi commented
@Fox2Code @osm0sis

2021-11-20 12:43 UTC, vvb2060 commented
@Gong-Mi 我们正在寻找通用的解决方案，不能是仅仅针对某些设备的专用版本。对于正常的大多数设备，这个值需要是3以禁用avb验证，0代表不禁用，将导致无法开机。因此，你可以在这些设备的论坛分发此专用版本，但不要在这里，可能会形成误导。

2021-11-20 12:55 UTC, Gong-Mi commented
> @Gong-Mi 我们正在寻找通用的解决方案，不能是仅仅针对某些设备的专用版本。对于正常的大多数设备，这个值需要是3以禁用avb验证，0代表不禁用，将导致无法开机。因此，你可以在这些设备的论坛分发此专用版本，但不要在这里，可能会形成误导。

那不是应该把那个1换成0吗

2021-11-20 14:05 UTC, Gong-Mi commented
> @Gong-Mi 我们正在寻找通用的解决方案，不能是仅仅针对某些设备的专用版本。对于正常的大多数设备，这个值需要是3以禁用avb验证，0代表不禁用，将导致无法开机。因此，你可以在这些设备的论坛分发此专用版本，但不要在这里，可能会形成误导。

那这样子呢https://github.com/Gong-Mi/Magisk/commit/dab69cce137b45526bb164468c47b7190c0b7f31
我试了k40g 生成的boot没有问题


然后这个问题应该就可以结束了吧
https://github.com/topjohnwu/Magisk/issues/4447

2021-11-20 14:37 UTC, Gong-Mi commented
> @Gong-Mi 我们正在寻找通用的解决方案，不能是仅仅针对某些设备的专用版本。对于正常的大多数设备，这个值需要是3以禁用avb验证，0代表不禁用，将导致无法开机。因此，你可以在这些设备的论坛分发此专用版本，但不要在这里，可能会形成误导。

主要是上一个测试版本测试过，k40g可以用

我以为就是加一个分之条件，然后小米升级到安卓12把系统更新错误退回给删除了
搞几次我还以为安卓12问题。
我退回到安卓11试了试，不行。
才发现这个bug，备注也写是0，代码写的是1😱😱

https://github.com/topjohnwu/Magisk/issues/4447#issuecomment-962793392

2021-11-20 14:44 UTC, osm0sis commented
> > @Gong-Mi 我们正在寻找通用的解决方案，不能是仅仅针对某些设备的专用版本。对于正常的大多数设备，这个值需要是3以禁用avb验证，0代表不禁用，将导致无法开机。因此，你可以在这些设备的论坛分发此专用版本，但不要在这里，可能会形成误导。
> 
> 那这样子呢[Gong-Mi@dab69cc](https://github.com/Gong-Mi/Magisk/commit/dab69cce137b45526bb164468c47b7190c0b7f31) 我试了k40g 生成的boot没有问题
> 
> 然后这个问题应该就可以结束了吧 #4447

Reverting to 0 is what I tried to do in #4901, but that breaks Samsung (as mentioned above), which is why we need a more general solution. 01 might work if it's written in the correct place. Not sure why it seems to be offset.

2021-11-20 14:46 UTC, yujincheng08 commented
> > @Gong-Mi 我们正在寻找通用的解决方案，不能是仅仅针对某些设备的专用版本。对于正常的大多数设备，这个值需要是3以禁用avb验证，0代表不禁用，将导致无法开机。因此，你可以在这些设备的论坛分发此专用版本，但不要在这里，可能会形成误导。
> 
> 那这样子呢[Gong-Mi@dab69cc](https://github.com/Gong-Mi/Magisk/commit/dab69cce137b45526bb164468c47b7190c0b7f31) 我试了k40g 生成的boot没有问题
> 
> 然后这个问题应该就可以结束了吧 #4447

应该要这样 https://github.com/topjohnwu/Magisk/pull/4906#issuecomment-963267639

2021-11-20 14:51 UTC, Gong-Mi commented
> > > @Gong-Mi 我们正在寻找通用的解决方案，不能是仅仅针对某些设备的专用版本。对于正常的大多数设备，这个值需要是3以禁用avb验证，0代表不禁用，将导致无法开机。因此，你可以在这些设备的论坛分发此专用版本，但不要在这里，可能会形成误导。
> > 
> > 那这样子呢[Gong-Mi@dab69cc](https://github.com/Gong-Mi/Magisk/commit/dab69cce137b45526bb164468c47b7190c0b7f31) 我试了k40g 生成的boot没有问题
> > 
> > 然后这个问题应该就可以结束了吧 #4447
> 
> Reverting to 0 is what I tried to do in #4901, but that breaks Samsung (as mentioned above), which is why we need a more general solution. 01 might work if it's written in the correct place. Not sure why it seems to be offset.

At least 1 is not right 
After all, the last time it was written is 0

2021-11-20 14:57 UTC, Gong-Mi commented
> > > @Gong-Mi 我们正在寻找通用的解决方案，不能是仅仅针对某些设备的专用版本。对于正常的大多数设备，这个值需要是3以禁用avb验证，0代表不禁用，将导致无法开机。因此，你可以在这些设备的论坛分发此专用版本，但不要在这里，可能会形成误导。
> > 
> > 那这样子呢[Gong-Mi@dab69cc](https://github.com/Gong-Mi/Magisk/commit/dab69cce137b45526bb164468c47b7190c0b7f31) 我试了k40g 生成的boot没有问题
> > 
> > 然后这个问题应该就可以结束了吧 #4447
> 
> 应该要这样 https://github.com/topjohnwu/Magisk/pull/4906#issuecomment-963267639

试过 3在k40g根本开不了机

1试过只能进rec ，但进不了系统。
而且可能会误导内核认为已经正常启动，但是系统认为没有。

0才能进系统并且一起正常。

2021-11-20 16:48 UTC, yujincheng08 commented
> 试过 1，2，3在k40g根本开不了机。 而且这个话题就是小米k40g，不能直接开机引出的提案引出的提交。
> 
> 删除这行能进rec，但是不能进系统。（我自己编写代码失误）
> 
> 0才能进系统并且一起正常。

你有在联系上下文？

2021-11-21 03:00 UTC, carey036 commented
> > @carey036 @ahxxm @qianmo-xw try the app-debug.apk in this Artifacts zip: https://github.com/topjohnwu/Magisk/actions/runs/1483248807
> 
> ~It seems that the patched boot.img has no change, same question with before.~

Sorry for my mistake, the origin code is "03 00 00 00 00 61 76 62 74 6F 6F 6C 20" rather than "03 00 00 00 00 00 00 00 00 61 76 62 74 6F 6F 6C 20".

so the new version changes "03 00 00 00 00 61 76 62 74 6F 6F 6C 20" to "01 00 00 00 00 61 76 62 74 6F 6F 6C 20" is  right.

but device can not boot with "01 00 00 00 00 61 76 62 74 6F 6F 6C 20"

2021-11-21 14:47 UTC, Fox2Code commented
@carey036 I do not have time to fully fix issue then, my health problems take too much of my energy right now to be able to continue making code and not risking my head to hurt again, I will still leave this issue open to keep track of the progress made.

I had a beginning of code to detect MIUI and OneUI ROMs on the Magisk App side if some want to take it:
```kotlin
    @JvmStatic val isOneUI: Boolean = try {
        Class.forName("android.os.SemSystemProperties")
        true
    } catch (e: ClassNotFoundException) {
        false
    }
    @JvmStatic val isMIUI: Boolean = try {
        Class.forName("android.content.res.MiuiTypedArray")
        true
    } catch (e: ClassNotFoundException) {
        false
    }
```
Source for MIUI code: https://twitter.com/diareuse/status/1452907383810822149?s=20
And for Samsung detection code I worked on a module to make Samsung apps work on AOSP
(Note: Never published module because of my health problems)

So both these method should be accurate to detect the ROM type.

2021-11-21 15:04 UTC, Gong-Mi commented
> @carey036 I do not have time to fully fix issue then, my health problems take too much of my energy right now to be able to continue making code and not risking my head to hurt again, I will still leave this issue open to keep track of the progress made.
> 
> I had a beginning of code to detect MIUI and OneUI ROMs on the Magisk App side if some want to take it:
> ```kotlin
>     @JvmStatic val isOneUI: Boolean = try {
>         Class.forName("android.os.SemSystemProperties")
>         true
>     } catch (e: ClassNotFoundException) {
>         false
>     }
>     @JvmStatic val isMIUI: Boolean = try {
>         Class.forName("android.content.res.MiuiTypedArray")
>         true
>     } catch (e: ClassNotFoundException) {
>         false
>     }
> ```
> Source for MIUI code: https://twitter.com/diareuse/status/1452907383810822149?s=20
> And for Samsung detection code I worked on a module to make Samsung apps work on AOSP
> (Note: Never published module because of my health problems)
> 
> So both these method should be accurate to detect the ROM type.

I'm sorry for my rudeness 
I didn't know about your health. Sorry 

It's all about this problem. It's been going on for a long time .

This issue involves MediaTek 1100,1200 and Xiaomi .

2021-11-24 06:14 UTC, closed without merging

2021-11-24 09:43 UTC, Gong-Mi commented
![Screenshot_2021-11-24-15-05-02-865_bin mt plus](https://user-images.githubusercontent.com/62661921/143214002-9d811cbb-72df-4c0e-a16d-0dfd4e0c1297.jpg)

2021-11-24 09:45 UTC, Kainpelikat commented
Yess

On Wed, 24 Nov 2021, 5:43 pm 汞齐, ***@***.***> wrote:

> [image: Screenshot_2021-11-24-15-05-02-865_bin mt plus]
> <https://user-images.githubusercontent.com/62661921/143214002-9d811cbb-72df-4c0e-a16d-0dfd4e0c1297.jpg>
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/topjohnwu/Magisk/pull/4906#issuecomment-977706000>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AVXBX3GQTP2WWBNQLJGRDELUNSXV3ANCNFSM5HSS4FHA>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>

2021-11-24 09:47 UTC, Gong-Mi commented
It doesn't seem to work at k40 G @Fox2Code 

https://github.com/topjohnwu/Magisk/actions/runs/1498084122

![Screenshot_2021-11-24-15-07-28-997_com topjohnwu magisk](https://user-images.githubusercontent.com/62661921/143214623-72229d41-bc07-4018-a238-d25092c35c4f.jpg)

2021-11-24 10:28 UTC, osm0sis commented
He didn't add the app side toggle for it yet.

2021-11-24 10:29 UTC, Gong-Mi commented
> He didn't add the app side toggle for it yet.

ok