Dump vendor_ramdisk_table and bootconfig from vendor_boot v4
topjohnwu/Magisk pull request #4974
Opened 2021-11-23 19:25 UTC by osm0sis

bootconfig is basically another cmdline with no size limit, and a vendor_ramdisk_table dump is needed currently for any potential external parsing of the vendor_boot v4 monolithic multi-ramdisk

2021-12-04 00:27 UTC, Daher-ALyaseen commented
> bootconfig is basically another cmdline with no size limit, and a vendor_ramdisk_table dump is needed currently for any potential external parsing of the vendor_boot v4 monolithic multi-ramdisk

2021-12-23 23:17 UTC, Ayaney approved these changes

2022-01-06 07:59 UTC, Mgthanlwin commented
fix/vndr4_dump

2022-01-12 21:25 UTC, osm0sis commented
Just leaving this open as a placeholder/issue until proper multi-ramdisk table/unpack/repack support can be added.

2022-01-23 07:00 UTC, jomir12 reviewed
[ Edit: Spam removed ]

2022-02-04 17:57 UTC, Sali41 requested changes
[084e0a7]()

2022-02-10 13:53 UTC, yujincheng08 commented
How about https://github.com/osm0sis/Android-Image-Kitchen. I would like to modify the bootconfig tho.

2022-02-10 21:05 UTC, osm0sis commented
Also planned, but both tools should support it. I'm on paternity leave starting any hour now, so no time for me any time soon.

2022-07-24 11:23 UTC, pumpi85 reviewed
native/jni/magiskboot/bootimg.cpp

2022-07-24 11:23 UTC, pumpi85 commented on native/jni/magiskboot/bootimg.cpp
> +    if (ver > 3 && is_vendor) {
native/jni/magiskboot/bootimg.cpp

2022-07-24 11:24 UTC, pumpi85 reviewed
native/jni/magiskboot/bootimg.cpp

2022-12-23 22:23 UTC, osm0sis commented
Filed a proper Issue to track this going forward: #6460

2022-12-23 22:23 UTC, closed without merging