Update RU strings
topjohnwu/Magisk pull request #5260
Opened 2022-01-24 08:14 UTC by VladWinner

2022-01-24 08:37 UTC, Displax requested changes

2022-01-24 08:37 UTC, Displax commented on app/src/main/res/values-ru/strings.xml
> +    <string name="home_notice_content">Скачивайте Magisk ТОЛЬКО из официального репозитория на GitHub. Файлы из других источников могут содержать вредоносный код!</string>
Думаю, КАПС тут не нужен. Некрасиво это...

2022-01-24 08:37 UTC, Displax commented on app/src/main/res/values-ru/strings.xml
> +    <string name="unsupport_nonroot_stub_msg">Пересобранное для скрытия приложение Magisk не может дальше продолжать работу, поскольку Root-права недоступны. Пожалуйста, восстановите приложение к исх
"не может дальше продолжать работу" упростить на "не может дальше работать"?

2022-01-24 08:37 UTC, Displax commented on app/src/main/res/values-ru/strings.xml
> +    <string name="unsupport_magisk_msg">Эта версия приложения Magisk не поддерживает версию Magisk ниже %1$s.\n\nПриложение будет работать так, словно Magisk не установлен вообще, пожалуйста, обновит
Думаю, "вообще" лишнее.

2022-01-24 08:37 UTC, Displax commented on app/src/main/res/values-ru/strings.xml
> +    <string name="zygisk_module_unloaded">Модуль Zygisk не загружен по причине несовместимости</string>
"Не запущен" будет лучше...

2022-01-24 08:37 UTC, Displax commented on app/src/main/res/values-ru/strings.xml
> +    <string name="touch_filtered_warning">Одно из приложений отображается поверх окна Magisk, выдача прав недоступна</string>
"Root-прав"

2022-01-24 09:09 UTC, Displax approved these changes

2022-01-24 20:32 UTC, Displax requested changes

2022-01-24 20:32 UTC, Displax commented on app/src/main/res/values-ru/strings.xml
> +    <string name="zygisk_module_unloaded">Модуль Zygisk не запущен по причине несовместимости</string>
"из-за несовместимости" лучше и короче

2022-01-25 06:30 UTC, topjohnwu approved these changes

2022-01-25 06:30 UTC, merged