Added es, ro & ca missing strings.
topjohnwu/Magisk pull request #5274
Opened 2022-01-25 17:42 UTC by ZillionMuffin

2022-01-25 17:52 UTC, ZillionMuffin commented
As I see I've made some accidental deletions, sorry about that.

2022-01-25 22:30 UTC, ArmynC requested changes
For the Romanian translation, there should be some changes. As an example, "Patchați" should be replaced by something around "Patchuiţi" for a 'mot-a-mot' way of writing, though there are other ways of doing it.

Next, for the "Modul suspendat pentru că %1$s este activat" you could do "Modulul este suspendat deoarece %1$s este activat" and so on for each iteration.

And finally, for the restore string, the term "ocultă" in this language has rather the meaning of a  paranormal thing/or a secret society. Instead, go for "Aplicaţia ascunsă va fi readusă la varianta iniţială. Sigur vreți să continuați?"

2022-01-26 05:48 UTC, ZillionMuffin commented
> For the Romanian translation, there should be some changes. As an example, "Patchați" should be replaced by something around "Patchuiţi" for a 'mot-a-mot' way of writing, though there are other ways of doing it.
> 
> Next, for the "Modul suspendat pentru că %1$s este activat" you could do "Modulul este suspendat deoarece %1$s este activat" and so on, for each iteration.
> 
> And finally, for the restore string. The term "ocultă" in this language has rather the meaning of a paranormal thing/secret society. Instead, go for "Aplicaţia ascunsă va fi readusă la varianta iniţială. Sigur vreți să continuați?"

I agree with that, gonna fix it later. My Romanian stills pretty basic.

2022-01-26 15:45 UTC, ZillionMuffin commented
On Spanish shouldn't be any error, only Catalan my have some missing things like l·l or ´,`

2022-01-27 21:40 UTC, vvb2060 commented
Please fix build

2022-01-28 16:49 UTC, ZillionMuffin commented
Right now the xml files should be good. I just fixed what the output says.

2022-01-29 11:22 UTC, Madis0 commented on app/src/main/res/values-ca/strings.xml
> +    <string name="patch_vbmeta">Modifiqueu vbmeta en l'imatge d'inici</string>
```suggestion
    <string name="patch_vbmeta">Modifiqueu vbmeta en l\'imatge d\'inici</string>
```
Apostrophes need to be escaped with `\`, that's probably why your builds are failing. Do the same change for other strings as well.

2022-01-29 19:53 UTC, ZillionMuffin commented
"unsupport_system_app_msg" is giving problems, gonna fix it if I have time tomorrow

2022-02-06 13:59 UTC, closed without merging