run module uninstall.sh on Magisk uninstallation
topjohnwu/Magisk pull request #6469
Opened 2022-12-25 18:06 UTC by HuskyDG

Currently Magisk does not run `uninstall.sh` script of modules when running Magisk's `uninstaller.sh`

2022-12-25 18:10 UTC, Displax commented
Confirm the problem

2022-12-26 05:33 UTC, alnabeel11 commented
شكرا جزيلا على المساعدة

2022-12-26 13:51 UTC, osm0sis requested changes
"Running module uninstallers" would better match the tense and grammar of the rest of the uninstaller output.

Good fix!

2022-12-26 14:53 UTC, osm0sis requested changes
Output should still be plural as "uninstallers" to emphasize it's doing it for any/all modules. Thanks!

2022-12-26 14:55 UTC, yujincheng08 requested changes
Why not directly `magisk --remove-modules`

2022-12-26 15:05 UTC, yujincheng08 commented
I don't think you should run third-party code during recovery (as it is now). Consider a module that wants to delete something in /data during uninstallation, but the /data is encrypted. You can check `BOOTMODE`, and only run `magisk --remove-modules` if it's not in the recovery.

2022-12-26 19:14 UTC, yujincheng08 commented
Maybe we can add an option to disable the reboot.

2022-12-26 19:33 UTC, yujincheng08 commented on native/src/core/magisk.cpp
> +        write_int(fd, 1);
```suggestion
        if (argc == 3 && argv[2] == "-n"sv) {
            write_int(fd, 0);
        } else if (argc == 2) {
            write_int(fd, 1);
        } else {
            usage();
            exit(1);
        }
```

2022-12-26 19:33 UTC, yujincheng08 commented on native/src/core/magisk.cpp
> +    } else if (argc > 2 && argv[1] == "--remove-modules"sv && argv[2] == "-n"sv) {
```suggestion
```

2022-12-26 19:35 UTC, yujincheng08 commented on native/src/core/magisk.cpp
> +   --remove-modules -n       remove all modules without reboot
```suggestion
   --remove-modules [-n]     remove all modules and reboot if -n is not given
```

2022-12-26 19:35 UTC, yujincheng08 commented on native/src/core/magisk.cpp
> +        return read_int(fd);
```suggestion
```

2022-12-26 19:39 UTC, yujincheng08 commented on native/src/core/daemon.cpp
>          break;
```suggestion
        break;
    }
```

2022-12-26 19:39 UTC, yujincheng08 commented on native/src/core/daemon.cpp
>      case MainRequest::REMOVE_MODULES:
```suggestion
    case MainRequest::REMOVE_MODULES: {
```

2022-12-26 19:44 UTC, yujincheng08 commented on native/src/core/magisk.cpp
>          int fd = connect_daemon(MainRequest::REMOVE_MODULES);
we should connect to daemon after checking the parameters

2022-12-26 20:04 UTC, yujincheng08 commented on native/src/core/daemon.cpp
> +    int do_reboot;
You dont need to put it here!

2022-12-26 20:05 UTC, yujincheng08 commented on native/src/core/magisk.cpp
> +            do_reboot=0;
format the code!!

2022-12-26 20:12 UTC, yujincheng08 commented on scripts/uninstaller.sh
> +ui_print "- Running module uninstallers"
Place it into the branch

2022-12-26 20:19 UTC, yujincheng08 approved these changes

2022-12-27 03:08 UTC, osm0sis commented
Considering the uninstaller does setup_flashable and mount_partitions it should be fine also having the originally PR'd script as an else for recovery running of the Magisk uninstaller, no? 🤔

2022-12-27 04:16 UTC, osm0sis approved these changes

2022-12-27 19:20 UTC, alnabeel11 commented
شكرا جزيلا على المساعدة


في الثلاثاء، ٢٧ ديسمبر ٢٠٢٢ ٧:١٧ ص Chris Renshaw ***@***.***>
كتب:

> ***@***.**** approved this pull request.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/topjohnwu/Magisk/pull/6469#pullrequestreview-1230334579>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A4TMS6O3DOMUAWONYD3RZ2TWPJUUHANCNFSM6AAAAAATJDDN4I>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>

2023-02-10 04:36 UTC, topjohnwu approved these changes

2023-02-10 04:36 UTC, merged