Refactor zygisk to use native bridge to inject
topjohnwu/Magisk pull request #6659
Opened 2023-03-01 15:25 UTC by yujincheng08

2023-03-01 15:57 UTC, canyie requested changes

2023-03-01 15:57 UTC, canyie commented on native/src/core/module.cpp
> +}
Close the fd `out`

2023-03-01 15:57 UTC, canyie commented on native/src/core/module.cpp
> +        auto prop_bk = MAGISKTMP + "/" ZYGISKBIN "/u:object_r:exported_dalvik_prop:s0";
Do not hardcode filename here

2023-03-01 15:57 UTC, canyie commented on native/src/core/module.cpp
> +        if (native_bridge.empty() || native_bridge == "0" || true) {
?

2023-03-01 15:57 UTC, canyie commented on native/src/include/magisk.hpp
> +#define NBPROPFILE      "/dev/__properties__/u:object_r:exported_dalvik_prop:s0"
DO NOT hardcode filename here

2023-03-01 15:57 UTC, canyie commented on native/src/zygisk/hook.cpp
> +// it should be safe to assume all dlcose's in libnativebridge is for zygisk_loader
Typo. It should be "dlclose"

2023-03-04 06:26 UTC, canyie requested changes

2023-03-04 06:26 UTC, canyie commented on native/src/init/rootdir.cpp
> +    mkfifo(dest, 0644);
Why do we have to use FIFO here?

```suggestion
    // Mock init.rc with our FIFO so we can change its content
    mkfifo(dest, 0644);
```

2023-03-04 06:26 UTC, canyie commented on native/src/init/rootdir.cpp
> +        return true;
```suggestion
        // Parent process (init), return and continue boot process
        return true;
```

2023-03-04 06:26 UTC, canyie commented on native/src/init/rootdir.cpp
> +    if (xfork()) {
```suggestion

    // Create a new process waiting for init operations
    if (xfork()) {
```

2023-03-04 06:26 UTC, canyie commented on native/src/init/rootdir.cpp
> +                mkfifo(zygote_dest, 0644);
Why do we have to use FIFO here?

2023-03-04 06:26 UTC, canyie commented on native/src/sepolicy/rules.cpp
> +    allow("init", "tmpfs", "file", "execute");
```suggestion
```

2023-03-04 06:26 UTC, canyie commented on native/src/zygisk/entry.cpp
> +    // we assume all zygotes have launched when systemui is launching
```suggestion
    // We assume all zygotes have launched when SystemUI is launching
    // So it's safe to reset native bridge at this time
```

2023-03-04 06:26 UTC, canyie commented on native/src/zygisk/hook.cpp
> +    void *load_native_bridge = nullptr;
```suggestion

    // Use unwind to find the address of LoadNativeBridge
    // and call it to load the real native bridge
    void *load_native_bridge = nullptr;
```

2023-03-04 15:40 UTC, canyie commented on native/src/init/rootdir.cpp
> +                              "re");
......

2023-03-04 15:40 UTC, canyie commented on native/src/init/rootdir.cpp
> +                "we");
......

2023-03-21 03:09 UTC, canyie approved these changes

2023-04-04 10:31 UTC, vvb2060 commented on native/src/init/rootdir.cpp
> +                fprintf(dest.get(), "    onrestart exec %s/magisk --zygote-restart\n", tmp_dir);
```suggestion
                fprintf(dest.get(), "    onrestart exec %2$s 0 0 -- %1$s/magisk --zygote-restart\n", tmp_dir, MAGISK_PROC_CON);
```

2023-04-08 22:20 UTC, vvb2060 commented on native/src/init/rootdir.cpp
> -    get_rand(&seed);
why

2023-04-10 19:20 UTC, vvb2060 commented on native/src/zygisk/entry.cpp
> +    if (getprop(NBPROP) == ZYGISKLDR && app_data_dir.ends_with("/com.android.systemui")) {
```suggestion
    if (app_data_dir.ends_with("/com.android.systemui" && getprop(NBPROP) == ZYGISKLDR)) {
```

2023-05-24 16:33 UTC, yujincheng08 commented on native/src/zygisk/entry.cpp
> +    zygisk_logging();
```suggestion
    rust::zygisk_entry();
```

2023-05-24 16:50 UTC, vvb2060 commented on native/src/zygisk/entry.cpp
> +    zygisk_logging();
my bad

2023-08-07 14:55 UTC, yashikada commented
After 2 months this PR is still valid? Will be accepted for the next stable release?
It seems to be a good job, it is bad to throw it away.

2023-11-08 08:16 UTC, topjohnwu commented
Merged into master manually

2023-11-08 08:16 UTC, closed without merging