Update Azerbaijani
topjohnwu/Magisk pull request #6845
Opened 2023-04-07 10:13 UTC by Gozzwip

2023-04-07 10:48 UTC, yujincheng08 requested changes

2023-04-07 10:48 UTC, yujincheng08 commented on app/src/main/res/values-az/strings.xml
> +    <string name="install_inactive_slot">Fəal olmayan Slot\'a quraşdır (OTA'dan sonra)</string>
```suggestion
    <string name="install_inactive_slot">Fəal olmayan Slot\'a quraşdır (OTA\'dan sonra)</string>
```

2023-04-07 10:48 UTC, yujincheng08 commented on app/src/main/res/values-az/strings.xml
> +    <string name="reboot_bootloader">Bootloader'ə başlat</string>
```suggestion
    <string name="reboot_bootloader">Bootloader\'ə başlat</string>
```

2023-04-07 11:36 UTC, Gozzwip commented
I dont know what to do about the 3rd check, some help would be appreciated

2023-04-09 04:14 UTC, topjohnwu approved these changes

2023-04-09 04:14 UTC, merged