Update strings.xml
topjohnwu/Magisk pull request #6987
Opened 2023-05-13 09:08 UTC by ErnestasKaralius

Updated all Lithuanian strings.

2023-05-14 16:52 UTC, yujincheng08 requested changes

2023-05-14 16:52 UTC, yujincheng08 commented on app/src/main/res/values-lt/strings.xml
> +    <string name="unsupport_general_title"Nenormali būsena</string>
```suggestion
    <string name="unsupport_general_title">Nenormali būsena</string>
```

2023-05-15 06:54 UTC, topjohnwu approved these changes

2023-05-15 06:54 UTC, topjohnwu approved these changes

2023-05-15 06:54 UTC, merged