typo fix
topjohnwu/Magisk pull request #7407
Opened 2023-10-06 11:13 UTC by nkh0472

2023-10-06 16:19 UTC, osm0sis commented
You introduced a new typo with your fixes...

2023-10-07 03:00 UTC, osm0sis requested changes
official

2023-10-07 14:57 UTC, nkh0472 commented
> You introduced a different typo with your typo fixes...

LOL, fixed

2023-10-07 19:53 UTC, osm0sis approved these changes

2023-10-10 00:22 UTC, merged